name: 'RPM Build'
description: 'Build RPM from spec file'
author: 'LukeR97'

inputs: 
  spec_file:
    description: '/config/discord_guild_updates.spec'
    required: true
    default: '*.spec' 
  additional_repos:
    description: 'A list of additional repositories to enable'
    required: false

outputs:
  source_rpm_path:
    description: 'path to Source RPM file'
  source_rpm_dir_path:
    description: 'path to  SRPMS directory'
  source_rpm_name:
    description: 'name of Source RPM file'
  rpm_dir_path:
    description: 'path to RPMS directory'
  rpm_content_type:
    description: 'Content-type for Upload'


